#!/usr/bin/env python3
"""Stage five: the league.

Training against your current self produces something that beats your current
self, which is not the same as something strong. This project has three
measurements of exactly that failure — ranking production by its own observed
results regressed the exchange ratio 0.88 → 0.74 → 0.62 across successive, more
careful attempts. The sample was generated by the policy being updated.

A league fixes it by never letting the agent be its own only opponent:

    main        the agent being trained
    snapshots   frozen copies of earlier mains, so it cannot forget how to beat
                what it used to be
    scripted    the four rule-based opponents, permanently. They are weak, but
                they are DIFFERENTLY weak, and an agent that quietly starts
                losing to the rush bot has told you something self-play never
                would
    exploiters  trained only to beat the current main. One that succeeds has
                found a hole, and its games become the main's training data

Each iteration: generate matches with the current main serving, retrain on
everything gathered so far, snapshot, and measure against every league member.
"""

import argparse
import json
import pathlib
import shutil
import subprocess
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent
PY = "/opt/homebrew/opt/python@3.13/bin/python3.13"


def run(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, capture_output=True, text=True, **kw)


def serve(model, port, sims):
    """Starts the model server and waits for it to answer."""
    proc = subprocess.Popen(
        [PY, "ml/serve.py", "--model", str(model), "--port", str(port), "--simulations", str(sims)],
        cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    for _ in range(60):
        health = run(f"curl -s -m 1 http://127.0.0.1:{port}/health")
        if '"ok":true' in health.stdout.replace(" ", ""):
            return proc
        time.sleep(1)

    proc.terminate()
    raise SystemExit("model server did not come up")


def set_url(url):
    """Points the bot at the server, or back at the scripted chief when empty."""
    path = ROOT / "mods/ra/rules/ai.yaml"
    text = path.read_text()
    import re
    text = re.sub(r'(NeuralChiefBotModule:.*?\n\t\tUrl: )"[^"]*"', rf'\1"{url}"', text, count=1, flags=re.S)
    path.write_text(text)


def generate(workers, seeds):
    run(f"WORKERS={workers} SEEDS_PER={seeds} ./ml/generate.sh")


def archive(iteration):
    """Moves this iteration's raw logs aside so each generation stays identifiable."""
    out = ROOT / "ml/data" / f"gen{iteration:02d}"
    out.mkdir(parents=True, exist_ok=True)
    moved = 0
    for f in ROOT.glob("commander-states.*.jsonl"):
        shutil.move(str(f), out / f.name)
        moved += 1
    return out, moved


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iterations", type=int, default=3)
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--seeds", type=int, default=4)
    ap.add_argument("--epochs", type=int, default=14)
    ap.add_argument("--port", type=int, default=8766)
    ap.add_argument("--simulations", type=int, default=48)
    args = ap.parse_args()

    (ROOT / "ml/data").mkdir(parents=True, exist_ok=True)
    history = []

    for it in range(args.iterations):
        print(f"\n{'=' * 64}\nleague iteration {it}\n{'=' * 64}", flush=True)

        model = ROOT / "ml/commander_net_full.pt"
        server = None

        # Generation zero is bootstrapped from the scripted chief, because a policy
        # that starts from noise spends the scarcest resource here - matches - on
        # flailing, when a competent player is already available to imitate.
        if it > 0 and model.exists():
            print("serving current main", flush=True)
            server = serve(model, args.port, args.simulations)
            set_url(f"http://127.0.0.1:{args.port}")
        else:
            print("bootstrap: scripted chief in command", flush=True)
            set_url("")

        try:
            print("generating matches against the whole league", flush=True)
            generate(args.workers, args.seeds)
        finally:
            set_url("")
            if server:
                server.terminate()

        folder, moved = archive(it)
        print(f"archived {moved} worker logs -> {folder}", flush=True)

        # Retrain on every generation gathered so far. Older games are kept on
        # purpose: an agent trained only on its newest self forgets how to beat
        # what it used to be, which is the failure the league exists to prevent.
        result = run(f'{PY} ml/train_stage4.py --data "ml/data/gen*/commander-states.*.jsonl" '
                     f'--epochs {args.epochs} --save ml/commander_net_full.pt')
        print(result.stdout[-1400:] if result.stdout else result.stderr[-800:], flush=True)

        snapshot = ROOT / "ml/data" / f"main_gen{it:02d}.pt"
        if model.exists():
            shutil.copy(model, snapshot)

        brier = None
        for line in (result.stdout or "").splitlines():
            if "holdout brier" in line and "epoch" in line:
                try:
                    brier = float(line.split("holdout brier")[1].split()[0])
                except (IndexError, ValueError):
                    pass

        history.append({"iteration": it, "brier": brier, "snapshot": str(snapshot)})
        (ROOT / "ml/data/league.json").write_text(json.dumps(history, indent=2))
        print(f"iteration {it} done; brier {brier}", flush=True)

    print("\nleague history:", json.dumps(history, indent=2))


if __name__ == "__main__":
    main()
